// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OwnedDataTest.Module.BusinessObjects;

#nullable disable

namespace OwnedDataTest.Module.Migrations
{
    [DbContext(typeof(OwnedDataTestEFCoreDbContext))]
    [Migration("20240620193413_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", true)
                .HasAnnotation("Proxies:CheckEquality", true)
                .HasAnnotation("Proxies:LazyLoading", false)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DevExpress.ExpressApp.EFCore.Updating.ModuleInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssemblyFileName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsMain")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ModulesInfo");
                });

            modelBuilder.Entity("OwnedDataTest.Module.BusinessObjects.Parent", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("OwnedDataTest.Module.BusinessObjects.Parent", b =>
                {
                    b.OwnsOne("OwnedDataTest.Module.BusinessObjects.Child", "Child", b1 =>
                        {
                            b1.Property<Guid>("ParentID")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.Property<string>("Other")
                                .HasColumnType("longtext");

                            b1.HasKey("ParentID");

                            b1.ToTable("Parents");

                            b1.WithOwner()
                                .HasForeignKey("ParentID");
                        });

                    b.Navigation("Child");
                });
#pragma warning restore 612, 618
        }
    }
}
